### ISSUE TITLE
image not showing in shop

### ISSUE THREAD

**Issue by amanmisri** [vanilophp/demo#19]
i tried to upload image via admin panel but it is not showing in  shop

**Comment by fulopattila122** [comment]
Please check #17 - it's likely the same problem.
Feel free to reopen the issue if it's not your case.

**Comment by amanmisri** [comment]
can you tell me what changes are to be done in APP_URL

**Comment by amanmisri** [comment]
I tried to change but nothing happened

**Comment by fulopattila122** [comment]
Put the base url of your application there
https://webdevetc.com/programming-tricks/laravel/general-laravel/why-should-you-update-app-url-from-from-http-localhost

Also did you run artisan storage:link ?

I try to help but you need to provide more Information.

**Comment by amanmisri** [comment]
> I tried to change but nothing happened



> Put the base url of your application there
> https://webdevetc.com/programming-tricks/laravel/general-laravel/why-should-you-update-app-url-from-from-http-localhost
> 
> Also did you run artisan storage:link
i run this command and also but the base url of application
i am running on localhost

**Comment by fulopattila122** [comment]
Please read thoroughly the linked issue, especially this comment:
https://github.com/vanilophp/demo/issues/17#issuecomment-451095634

Please put your answers to the questions in that comment.

Please also note that your issue is not specific to this project but basic Laravel configuration.
Even then, I'm happy to help if you're giving me relevant Information and not wanting me to figure out all the details you should've provided: https://stackoverflow.com/help/how-to-ask

**Comment by amanmisri** [comment]
i tried to run the command php artisan storage:link.nothing happened
i also try to chcange the app_url for www.localhost to http://localhost/{E-mandi}/public/images but same error is occuring

**Comment by fulopattila122** [comment]
APP_URL is either `http://localhost` or `http://localhost:8000` or `http://127.0.0.1:8000`.
Also, the question I've mentioned was that what is the exact HTTP error 404 or 403 you get in the browser for pictures?

As far as I see you need to learn a bit more about the basics of web development. Especially: what is a URL what are local and remote hostnames, how does DNS work and what are web paths. Laravel is not a complex framework but you need to have a basic understanding of these concepts in order to make it work.

**Comment by amanmisri** [comment]
I appreciate for ur help 
I was doing as it was suggested in this https://laracasts.com/discuss/channels/laravel/app-url?page=0
that why i was entering full path
