### ISSUE TITLE
Default front end theme

### ISSUE THREAD

**Issue by karneaud** [vanilophp/demo#48]
Are there default themes for Vanilo? Are there any recommended theme built or compatible with vanilo?

**Comment by fulopattila122** [comment]
Hi, there are no themes as Vanilo is not supplying a frontend.

The reason behind this is that Vanilo components/framework was targeted for Laravel developers, and it wants to be as unobtrusive as possible. This demo repository was made exactly to give a loose guideline on how you can assemble a shop yourself with a simple setup.

So this is intentional, as we wanted to leave complete freedom for developers.

Nevertheless, there are plans to add more examples, especially the vue-storefrontend is highly demanded.

**Comment by fulopattila122** [comment]
Does the example in this repository give you a sufficient guide to starting? If not, let me know where you have stuck.

**Comment by karneaud** [comment]
@fulopattila122 thanks for the feedback. Will have a close look. usually I look at using https://github.com/caffeinated/themes but thought that you guys would have your own rollout. Will see how this works out and let you know
