### ISSUE TITLE
One product have multiple property values?

### ISSUE THREAD

**Issue by benjaminv** [vanilophp/demo#79]
Thanks for the great work guys. I just tried Vanilo demo from this repo. It is very inspiring that it works with Laravel as a package and to the best keep laravel itself intact. 
I might be doing it wrong but could a product have multiple properties values? For instance a mattress model, to have various sizes like KQDS and KS? When I test-drove it one listing (sku) can only choose one value per property. Appreciate.

**Comment by fulopattila122** [comment]
The idea is that product variants are separate entries, as they have separate stocks.
As an example, given a specific kind of mattress having 5 pcs of size KS, 3 pcs of KQDS, and let's say out of stock for toddler size. Thus they are supposed to have different SKUs - since each SKU has a single stock figure.

I also understand that not all businesses work alike and I would be happy if you could explain your use case and how do you handle (or would like to handle) such situations.

Cheers
