### ISSUE TITLE
Demo Data missing

### ISSUE THREAD

**Issue by upeksha1996** [vanilophp/demo#8]
I followed the instructions, but demo data was not there. Even seed contains only country names.

**Comment by fulopattila122** [comment]
Hello,

There's no demo data included.

You have to add products yourself using the backend.

**Comment by upeksha1996** [comment]
Ah okay :D It would be really easy though.. I can add some seeds if you want.

**Comment by pedroreartes** [comment]
so... if no demo data... is this a "demo"? 
what is the difference then with an installation with composer?
thanks! 
Grate work

**Comment by fulopattila122** [comment]
The main focus of the demo is to show how to build your storefront by providing an example application.
The framework is neither an application nor provides storefront functionality out of the box.
This is not a shortcoming but a very intentional decision. One of the main aims of the framework is to leave freedom for the application developer.

So the main part of the demo is the [app/Http/Controllers](https://github.com/vanilophp/demo/tree/0.5/app/Http/Controllers) folder, where you have intentionally simple examples of building your storefront pages like:
- product index,
- categorization,
- filtering,
- product singles,
- cart,
- checkout.

**Comment by pedroreartes** [comment]
Great! Thanks!
